./Main_sam.sh norm english 0 0 5 3 ensemble_test
./Main_sam.sh norm english 0 1 5 3 ensemble_test
./Main_sam.sh norm english 0 2 5 3 ensemble_test
./Main_sam.sh norm english 0 3 5 3 ensemble_test
./Main_sam.sh norm english 0 4 5 3 ensemble_test
./Main_sam.sh norm english 0 5 5 3 ensemble_test
./Main_sam.sh norm english 0 6 5 3 ensemble_test
./Main_sam.sh norm english 0 7 5 3 ensemble_test
./Main_sam.sh norm english 0 8 5 3 ensemble_test
./Main_sam.sh norm english 0 9 5 3 ensemble_test
./Main_sam.sh norm german 0 0 5 3 ensemble_test
./Main_sam.sh norm german 0 1 5 3 ensemble_test
./Main_sam.sh norm german 0 2 5 3 ensemble_test
./Main_sam.sh norm german 0 3 5 3 ensemble_test
./Main_sam.sh norm german 0 4 5 3 ensemble_test
./Main_sam.sh norm german 0 5 5 3 ensemble_test
./Main_sam.sh norm german 0 6 5 3 ensemble_test
./Main_sam.sh norm german 0 7 5 3 ensemble_test
./Main_sam.sh norm german 0 8 5 3 ensemble_test
./Main_sam.sh norm german 0 9 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 0 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 1 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 2 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 3 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 4 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 5 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 6 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 7 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 8 5 3 ensemble_test
./Main_sam.sh norm indonesian 0 9 5 3 ensemble_test
